server:
  port: 8088
  max-http-header-size: 2MB

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  application:
    name: spring-training
  jackson:
      serialization:
        write-dates-as-timestamps: false
      time-zone: America/Mexico_City
      mapper:
        default-view-inclusion: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:training}?useTimezone=true&amp;serverTimezone=America/Mexico_City
    username: ${DB_USER:admin}
    password: ${DB_PASS:password}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
  jpa:
      show-sql: false
      hibernate:
            naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      database-platform: org.hibernate.dialect.MySQL5Dialect
      properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
            hibernate.format_sql: false
            hibernate.show_sql: false

springfox:
  documentation:
    swagger:
      v2:
        path: /requests/api/docs

swagger:
  enabled: ${SWG_ENABLED:true}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    io.lkmx.maypo.portal: ${APP_LOG_LEVEL:INFO}

